### ISSUE TITLE
Missing LP and not showing

### ISSUE THREAD

**Issue by Rico210280** [FalconX-DEX/Falx-Support#85] opened 2024-11-23 18:25 UTC
A deposit to liquidity (sol-falx) is missing/not showing, send 4 sol and 2,3 M Falx (wallet adress: 

4y9GzYfv6E6NgXG3Du46DJjn36MwRq58N4jWNoVx1BDE

![Screenshot_20241123_015556_Chrome](https://github.com/user-attachments/assets/09459d53-23d2-4ae0-ae82-f6190de63a83)

Thank you, Rico

**Comment by Tony-ptech** [comment] 2024-11-23 18:29
> A deposit to liquidity (sol-falx) is missing/not showing, send 4 sol and 2,3 M Falx (wallet adress:
> 
> 4y9GzYfv6E6NgXG3Du46DJjn36MwRq58N4jWNoVx1BDE
> 
> ![Screenshot_20241123_015556_Chrome](https://private-user-images.githubusercontent.com/189475028/389218673-09459d53-23d2-4ae0-ae82-f6190de63a83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODY3OTUsIm5iZiI6MTczMjM4NjQ5NSwicGF0aCI6Ii8xODk0NzUwMjgvMzg5MjE4NjczLTA5NDU5ZDUzLTIzZDItNGFlMC1hZTgyLWY2MTkwZGU2M2E4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxODI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWM0YTk3OGM4NjM5ZWQzMzc3ZjY0NGVmZGNlYmI4ZGUyM2U2NDJmYTBiMmUyYWQwY2Y1ZTBkMDY0NDJmN2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sUp0PlfNpcc5qAqKwcoQp6KP8gsbOwHrds3K8ZQf4U4)
> 
> Thank you, Rico

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Falx Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Lissanro** [comment] 2024-11-23 18:55
Warning: the comment from a scammer who offered to join a fake "support line" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Rico210280** [comment] 2024-11-25 17:46
Good evening Github team, 

can you tell me approximately how long it will take until my coins are back in my wallet? Thank you. 

Best Regards Rico

**Comment by Lissanro** [comment] 2024-11-26 12:43
The issue should be fixed. Please check, if your investment showed up in the pools.

**Comment by Rico210280** [comment] 2024-11-26 14:13
Coins arrived. Thank you so much.

Best regards Rico

**Closed as completed** 2024-11-26 14:14 UTC
Labels: in triage  🔍
