### ISSUE TITLE
Unable to add liquidity 

### ISSUE THREAD

**Issue by Digital1989** [FalconX-DEX/Falx-Support#80] opened 2024-10-31 07:43 UTC
My issue is I can’t add liquidity even though I have some. I’m not sure if it’s a bug. I’ve asked everyone but every time I try to add more liquidity and it doesn’t matter the slippage or how much I change it to. I get the same thing. Which I’ve provided screen shots. I have closed all tabs and everything it won’t let me add liquidity.I have added liquidity with USDC but my solana won’t work and I already bought a small amount 2$ into the pool and when I try to add to it it’s same thing. I am 
![IMG_3776](https://github.com/user-attachments/assets/a439150e-79f8-4dec-891d-fabc973d88f9)
![IMG_3775](https://github.com/user-attachments/assets/047dc588-e6e2-499e-8810-fa915db25570)
on a iPhone. And my wallet address is 78mHh25a3ucPMAqdGQfush1N2xQ4qD1TYcCwhJEX1Kh3

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Elsiehwoods** [comment] 2024-10-31 12:51
@Digital1989  Given that you’ve already tried adjusting the slippage and closing all tabs, it might be helpful to check if your Phantom wallet is properly connected and has the necessary permissions. Sometimes, clearing the cache or using a different browser can also resolve such issues. If the problem persists, it might be a bug with the dapp itself

**Comment by Lissanro** [comment] 2024-10-31 17:00
Please specify to what pool you are trying to add? If it is for FALX-USDC, please note that you need to have enough of both FALX and USDC.

**Comment by Digital1989** [comment] 2024-10-31 17:07
It’s the falx to sol the very first pool. I have 2.86 in the pool already
but it won’t let me add or remove it. It just says that same thing and I
have enough sol and falx

**Comment by Digital1989** [comment] 2024-11-01 04:08
Sometimes it’s says provide correct hash after I cancel it. Cause it’s say
what’s in the picture

**Comment by Lissanro** [comment] 2024-11-15 03:51
We had some updates recently. Could you please check if the issue is resolved?

**Comment by Digital1989** [comment] 2024-11-16 00:10
Yes I will do it tonight thank you

**Comment by Lissanro** [comment] 2024-11-23 18:52
Since since other users with similar issue at the time reported it solved, I am assume this issue is fixed. If still does not work on your end, please let us know.

**Closed as completed by Lissanro** 2024-11-23 18:52 UTC
Labels: in triage  🔍

**Comment by Digital1989** [comment] 2024-11-23 18:54
Yes sorry I been busy and haven’t been able to email you. But yes it works
and o haven’t had any issues  thank you. 🚀🚀
