### ISSUE TITLE
Price chart does not refocus

### ISSUE THREAD

**Issue by Tdjc919** [FalconX-DEX/Falx-Support#45] opened 2024-09-09 05:09 UTC
When looking at the price chart in the swap page of the app, I can see the price of FALX. However, when selecting a different token the chart does not recalibrate to show the price of that token. If you zoom-out and scroll you eventually find the graph, but it should automatically find the price graph.

**Smartphone (please complete the following information):**
 - Device: SAMSUNG A52
 - OS: Android
 - Browser Phantom wallet browser
 - Version (?)

**Additional context**

**Comment by Lissanro** [comment] 2024-09-10 08:22
Could you please share exact steps to reproduce, a screenshot of what you are getting at first, and a screenshot of what you expected to get automatically? It would help to understand the issue better. Thanks.

**Comment by Tdjc919** [comment] 2024-09-10 20:58
https://github.com/user-attachments/assets/4d71a721-2c99-4116-9b2d-fa16bc7364a2

**Comment by Tdjc919** [comment] 2024-09-14 11:53
It is now completely broken... 

![Screenshot_20240914_135134_Phantom](https://github.com/user-attachments/assets/ab1436f0-3406-4703-b11f-e80473ee2309)

**Comment by Tdjc919** [comment] 2024-09-14 11:55
Oh I see it does refocus now. Only the chart of falx is very weird. And it only loads part of the time series.

**Comment by Lissanro** [comment] 2024-09-14 13:09
No, it is full time series being loaded. The reason why it does not go very far in the past is because we launch our own router and liquidity pool, so it does not yet have a long history. The previous liquidity pool is also there of course, but the main focus are our own pools, when they are available, so this is what the chart shows by default.

I am going to close this bug report because it was files against the old chart implementation. The new one is quite different under the hood, and has slightly different look also. If you encounter issues with the new chart, please report them as a separate bug report. Thank you.

**Closed as completed by Lissanro** 2024-09-14 13:09 UTC
Labels: in triage  🔍
