### ISSUE TITLE
At least in the swap. 

### ISSUE THREAD

**Issue by ino89** [FalconX-DEX/Falx-Support#54] opened 2024-09-15 10:00 UTC
- OS: Android
Browser Phatom

Hello! I don't know if it's a problem or wanted. I can only use at least 1 sol for swaps (not 0.4 sol) Is that what he wants?

**Comment by Lissanro** [comment] 2024-09-15 10:44
No, it should be possible to enter any amount, including 0.4 SOL. I tested using Phantom on Android, and it works for me.
![Screenshot_20240915_104126_Phantom](https://github.com/user-attachments/assets/626ff635-8727-45e3-a95e-eac1b1c482c2)
Could you describe what happens exactly when you try to enter 0.4 as the exchange amount?

**Comment by ino89** [comment] 2024-09-15 11:24
https://github.com/user-attachments/assets/3b2baa43-e74b-48ea-8e31-a2c4c6d62096

 
I'm not going to see video.

**Comment by ino89** [comment] 2024-09-15 11:25
Samsung s23 ultra latest version of Android

**Comment by Tdjc919** [comment] 2024-09-15 17:56
Same problem as my ticket

**Comment by ino89** [comment] 2024-09-15 18:02
I could still find an ad error at pools. Watch the video 

https://github.com/user-attachments/assets/164e89ce-5864-4fc3-9150-a01628ad2a97

**Comment by Lissanro** [comment] 2024-09-16 14:19
The issue may have been caused by locale settings. This should be fixed. In case the issue still occurs after refreshing the page, please let me know.

**Closed as completed by Lissanro** 2024-09-16 14:19 UTC
Labels: in triage  🔍

**Comment by ino89** [comment] 2024-09-16 15:54
So with me it's still not possible now no more comma goes.

**Comment by Lissanro** [comment] 2024-09-16 16:17
On my end entering the comma automatically converts it to a decimal point both on desktop and mobile devices I tested with.

That said, I pushed additional possible fix, please try again and if there is still an issue, please let me know.

**Comment by ino89** [comment] 2024-09-16 16:23
> On my end entering the comma automatically converts it to a decimal point both on desktop and mobile devices I tested with.
>
> That said, I pushed additional possible fix, please try again and if there is still an issue, please let me know.

I don't know. It's already phantom in English. I made a new video

**Comment by ino89** [comment] 2024-09-16 16:24
Uploading Screen_Recording_20240916_182017_Phantom.mp4…

**Comment by ino89** [comment] 2024-09-16 16:44
https://github.com/user-attachments/assets/c5344714-5832-451b-8d0d-4cc5ad7800b4

**Comment by ino89** [comment] 2024-09-16 16:45
https://github.com/user-attachments/assets/3f66d2ea-7fa1-4ff0-8037-ecb181a33d59

**Comment by ino89** [comment] 2024-09-16 16:45
https://github.com/user-attachments/assets/ca50117f-9bd2-4817-9ed4-e75cfe5dc98b

**Comment by Lissanro** [comment] 2024-09-16 19:36
I changed the implementation for the input field in way that should be compatible with all browser and device combinations, so it should be fixed now, but please let me know if you still encounter the issue.

**Comment by ino89** [comment] 2024-09-16 19:39
It works thanks for the quick processing 

Great job you do!
