### ISSUE TITLE
SolX AIRDROP 

### ISSUE THREAD

**Issue by Cooliee2k** [FalconX-DEX/Falx-Support#28] opened 2024-07-21 22:38 UTC
hello,

I did not recieve my SolX airdrop to one of my walllets submitted on the form. I am quite frustrated because I definatly filled out the form well within the timeframe, I asked in the group chat for help and even had a DM conversation with Matt to try and ensure I did it correctly. I have seen Matt say in the chat that if the form wasnt filled out in the timeframe you guys cannot help, but as mine was filled out correctly and within the time frame i would expect to still qulify for the airdrop.

There is proof available of my purhase and stake from my wallet hitstory. The account in question is ; FZdmbNcQMfxnjDm1RWYhLoFgZqCKHandkyz3TfbiVVFf

i also had another account staking but i need to access another device to check that, so if that is not recvied either i can create another ticket.

**Comment by Lissanro** [comment] 2024-07-21 22:42
Duplicate of #27 (please open only one issue per wallet address).

**Closed as completed by Lissanro** 2024-07-21 22:42 UTC
