### ISSUE TITLE
Unable to harvest

### ISSUE THREAD

**Issue by awddal2001** [FalconX-DEX/Falx-Support#77] opened 2024-10-23 20:48 UTC
**Describe the bug**

**To Reproduce**
1. Go to '... Staking 
2. Click on '....' falcon 
3. Scroll down to '....' harvest

**Expected behavior**

The amount I have earnt through staking to be harvested 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] appo16
 - OS: [e.g. iOS8.1] unsure
 - Browser [e.g. stock browser, safari] chrome

**Additional context**

**Comment by LeoNore-ort** [comment] 2024-10-24 00:12
@awddal2001 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Falx / Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Lissanro** [comment] 2024-10-24 00:55
Warning: the comment from a scammer who offered to join fake "support line" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Lissanro** [comment] 2024-10-24 00:56
Duplicate of #76 - please subscribe to it in case you want to keep track of the bug report.

**Closed as completed by Lissanro** 2024-10-24 00:56 UTC
